version: '3'
services:
  web:
    build: .
    container_name: gesformation
    ports:
      - "8089:8082"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always

    environment:
      MYSQL_DATABASE: testF #Create an initial empty database called webserver
      MYSQL_ROOT_USER: root #root user
      MYSQL_ROOT_PASSWORD:   #root password
      MYSQL_ROOT_HOST: '%' 